apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springtest
  name: springtest
  namespace: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springtest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springtest
    spec:
      containers:
      - image: springtest/latest
        name: latest
        resources: {}
        imagePullPolicy: Never
        ports:
          - containerport: 8080
---
