apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springtest
  name: springtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springtest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springtest
    spec:
      containers:
      - image: springtest/latest
        name: latest
        resources: {}
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: stacionar.dumbo
spec:
  type: ExternalName
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: db-server
subsets:
  - addresses:
      - ip: 10.10.0.10
    ports:
      - port: 5432