spring:
    application:
        name: springtest
    datasource:
        url: jdbc:postgresql://10.10.0.6:5432/test_user
        username: test_user
        password: hellothere
        hikari:
            connectionTimeout: 30000 
            maxLifetime: 1800000
            idleTimeout: 600000