spring:
    application:
        name: springtest
    datasource:
        url: jdbc:postgresql://stacionar.dumbo:5432/springtest
        username: test_user
        password: hellothere
        hikari:
            connectionTimeout: 30000 
            maxLifetime: 1800000
            idleTimeout: 600000

logging:
    level:
        org.springframework.web: DEBUG
        org.springframework.security.config.core: DEBUG
        org.springframework.security.web: DEBUG