- name: Ping my hosts
  ping:
  
- name: debug froups
  debug:
    msg: "{{ group_names }}"
# - name: Create Temp Dir
#   tempfile:
#     state: directory
#     suffix: templates
#   register: temp_dir
#   when: "'application' in {{group_names}}"

# # - name: DEbug template
# #   debug:
# #     msg: "{{ lookup('ansible.builtin.template', 'templates/main.j2') }}"

# - name: Template files
#   template:
#     src: "{{ item }}"
#     dest: "{{ temp_dir.path }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
#   with_fileglob:
#     - templates/*.j2
#   when: "'application' in {{group_names}}"


# # - name: Show current path
# #   debug:
# #     msg: "{{ playbook_dir }}"

# - name: Copy templates
#   copy:
#     src: "{{ temp_dir.path }}/"
#     dest: "{{ playbook_dir }}/../"
#   when: "'application' in {{group_names}}"


# # - name: Copy files
# #   copy:
# #     src: files/
# #     dest: "{{ resource_dir }}"