#Application
application_host: stacionar.dumbo
application_port: 8080  

#NGINX
resource_dir: /var/www/resources
nginx_sites_conf_dir: /opt/homebrew/etc/nginx/sites-available
nginx_conf_dir: /opt/homebrew/etc/nginx/